DATA:
  data_root: dataset/voc2012
  train_list: dataset/voc2012/list/train_aug.txt
  val_list: dataset/voc2012/list/val.txt
  classes: 21

TRAIN:
  arch: unet
  backbone: convnext_tiny
  optimizer: adamw
  pretrained: True
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  train_h: 256
  train_w: 256
  criterion: cross_entropy #
  use_cosine_annealing: True
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  #train_gpu: [0, 1]
  #train_gpu: [0, 1, 2, 3] 
  workers: 64  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  epochs: 250
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.05
  manual_seed:
  print_freq: 100
  save_freq: 1
  save_path: runs/unet/voc2012/trial_accuracy/model
  weight:  #/work/ws-tmp/sa058646-segment2/semseg/runs/new_exp_slak/voc2012/unet/SLaK_tiny_trans_kernel_2_small_trans_0_convnext_backbone_False_backbone_kernel_3_small_conv_0/model/train_epoch_250.pth
  resume:  #/work/ws-tmp/sa058646-segment2/semseg/runs/new_exp_slak/voc2012/unet/SLaK_tiny_trans_kernel_2_small_trans_0_convnext_backbone_False_backbone_kernel_3_small_conv_0/model/train_epoch_250.pth
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

   #LARGE KERNEL
  Decom: True
  width_factor: 1.3
  kernel_size: [51, 49, 47, 13, 5]
  trans_kernel: 2
  backbone_kernel: 3
  small_trans: 0 #3
  small_conv: 0 #3
  use_convnext_backbone: False
  freq_upscale: False

TEST:
  test_list: dataset/voc2012/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 256
  test_w: 256
  testing: False
  binarize: True
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0, 1]
  epsilon: 0.03
  alpha: 0.01
  iterations: 20
  model_path: /work/ws-tmp/sa058646-segment/semseg/runs/new_exp_slak/voc2012/unet_11/convnext_tiny_trans_kernel_2_small_trans_0_convnext_backbone_False_backbone_kernel_3_small_conv_0/model/train_epoch_250.pth
  save_folder: /work/ws-tmp/sa058646-segment/semseg/runs/new_exp_slak_testing_freq_fgsm/voc2012/unet/convnext_tiny_trans_kernel_2_small_trans_0_convnext_backbone_False_backbone_kernel_3_small_conv_0/val/ss  # results save folder
  colors_path: data/voc2012/voc2012_colors.txt  # path of dataset colors
  names_path: data/voc2012/voc2012_names.txt  # path of dataset category names
